version: "3.7"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    working_dir: /workspaces/cryptcurrency_autotrade
    command: sleep infinity
    ports:
      - 4000:3000
    volumes:
      - ..:/workspaces/cryptcurrency_autotrade:cached
    env_file: ./.env
    tty: true
    environment:
      - LANG=C.UTF-8
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
